exports.info =
	name: 'default'
	version: '0.1.0'
	description: 'The first parametric typeface'
	'cap-height': 720
	'descendent-height': 210
	'glyph-order':
		'h': 'h'
		'8': 'eight'
		'o': 'o'
		'O': 'o_cap'
		'b': 'b'
		'c': 'c'
		'C': 'C'
		'i': 'i'
		'D': 'd_cap'
		'B': 'b_cap'
		'1': 'one'
		'k': 'k'
		'a': 'a'
		's': 's'
		'H': 'h_cap'
		'm': 'm'
		'n': 'n'
		'e': 'e'
		'M': 'm_cap'
		'0': 'test2'